Repository Linesmerrill/police-cad, pull requests merged in 2020-01, with the labels that each got.

#75 adds firearm status, adds Patreon link and fixes warrant display bug
  app/models/civilian.js
  app/routes.js
  public/css/styles.css
  views/about.html
  views/civ-dashboard.html
  views/ems-dashboard.html
  views/footer.html
  views/forgot-password.html
  views/index.html
  views/login-civ.html
  views/login-ems.html
  views/login-police.html
  views/page-not-found.html
  views/police-dashboard.html
  views/release-log.html
  views/reset.html
  views/rules.html
  views/signup-civ.html
  views/signup-ems.html
  views/signup-police.html
  views/terms-and-conditions.html
Labels: bug, enhancement

#76 Feature/update site title
  public/images/civ-bkground.jpg
  public/images/ems-bkground.png
  public/images/gta-landing-page.jpg
  public/images/hway_bkground.jpg
  public/images/star.png
  views/index.html
  views/rules.html
Labels: bug

#78 Cleanups and correctly using EJS.
  .env.example
  .gitignore
  README.md
  app.js
  app/routes.js
  config/database.js
  package-lock.json
  package.json
  views/about.ejs
  views/civ-dashboard.ejs
  views/ems-dashboard.ejs
  views/footer.ejs
  views/forgot-password.ejs
  views/index.ejs
  views/login-civ.ejs
  views/login-ems.ejs
  views/login-police.ejs
  views/page-not-found.ejs
  views/police-dashboard.ejs
  views/privacy-policy.ejs
  views/release-log.ejs
  views/reset.ejs
  views/rules.ejs
  views/signup-civ.ejs
  views/signup-ems.ejs
  views/signup-police.ejs
  views/terms-and-conditions.ejs
Labels: enhancement

#102 Feature/arrest report
  app/models/arrestReport.js
  app/routes.js
  public/css/styles.css
  views/police-dashboard.ejs
  views/release-log.ejs
Labels: enhancement, good first issue
